name: Test

on:
  push:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: neoetheilred/tgnotification@main
        with: 
          telegram_token: ${{secrets.TELEGRAM_TOKEN}}
          chat_id: ${{secrets.TELEGRAM_TO}}
          message: |
            multiline 
            message
            test

  
